In [1]:
from LorisBallsBasedModel import *
import tensorflow as tf
import pandas as pd
import numpy as np

In [2]:
X = [tf.random.uniform((10000, 3)),
     tf.random.uniform((10000, 3)),
     tf.random.uniform((10000, 3))]

X

[<tf.Tensor: shape=(10000, 3), dtype=float32, numpy=
 array([[0.5718638 , 0.21838808, 0.86348057],
        [0.16515756, 0.68862927, 0.44986165],
        [0.9789096 , 0.86461544, 0.7126527 ],
        ...,
        [0.27073896, 0.9006597 , 0.7541754 ],
        [0.10058415, 0.23088217, 0.73472023],
        [0.5383748 , 0.68833745, 0.4981618 ]], dtype=float32)>,
 <tf.Tensor: shape=(10000, 3), dtype=float32, numpy=
 array([[0.7014574 , 0.18497849, 0.75103366],
        [0.75598407, 0.18697977, 0.5655296 ],
        [0.234496  , 0.14560926, 0.17186439],
        ...,
        [0.8665807 , 0.8969635 , 0.36051667],
        [0.8009305 , 0.60470855, 0.75371337],
        [0.22140443, 0.72753227, 0.42680883]], dtype=float32)>,
 <tf.Tensor: shape=(10000, 3), dtype=float32, numpy=
 array([[0.15445781, 0.47623682, 0.35283446],
        [0.24855411, 0.2518226 , 0.11547804],
        [0.75009584, 0.10065734, 0.9997022 ],
        ...,
        [0.5313879 , 0.9693116 , 0.97751856],
        [0.53161085, 0.9298545

In [3]:
y = 2*X[0]

y

<tf.Tensor: shape=(10000, 3), dtype=float32, numpy=
array([[1.1437275 , 0.43677616, 1.7269611 ],
       [0.3303151 , 1.3772585 , 0.8997233 ],
       [1.9578192 , 1.7292309 , 1.4253054 ],
       ...,
       [0.5414779 , 1.8013194 , 1.5083508 ],
       [0.2011683 , 0.46176434, 1.4694405 ],
       [1.0767496 , 1.3766749 , 0.9963236 ]], dtype=float32)>

In [4]:
model = SingleLayerPerceptron(WeightedAdd(1))
model.compile(loss='mse', optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), metrics=['acc'])
model.fit(X, y, epochs=50, verbose=1)

Epoch 1/50
313/313 [==============================] - 1s 1ms/step - loss: 0.2785 - acc: 0.5877
Epoch 2/50
313/313 [==============================] - 0s 1ms/step - loss: 0.1488 - acc: 0.6737
Epoch 3/50
313/313 [==============================] - 0s 1ms/step - loss: 0.0881 - acc: 0.7621
Epoch 4/50
313/313 [==============================] - 0s 1ms/step - loss: 0.0492 - acc: 0.8294
Epoch 5/50
313/313 [==============================] - 0s 1ms/step - loss: 0.0257 - acc: 0.8780
Epoch 6/50
313/313 [==============================] - 0s 1ms/step - loss: 0.0126 - acc: 0.9127
Epoch 7/50
313/313 [==============================] - 0s 1ms/step - loss: 0.0059 - acc: 0.9389
Epoch 8/50
313/313 [==============================] - 0s 1ms/step - loss: 0.0027 - acc: 0.9583
Epoch 9/50
313/313 [==============================] - 0s 1ms/step - loss: 0.0012 - acc: 0.9727
Epoch 10/50
313/313 [==============================] - 0s 1ms/step - loss: 5.4549e-04 - acc: 0.9842
Epoch 11/50
313/313 [========================

In [5]:
model.output_layer.kernel

<tf.Variable 'single_layer_perceptron/weighted_add_2/kernel:0' shape=(3, 3) dtype=float32, numpy=
array([[ 2.00000000e+00,  2.00000000e+00,  2.00000000e+00],
       [ 1.62230750e-11,  1.28266755e-11, -4.25561392e-11],
       [-8.13044493e-11,  1.15138940e-10, -4.06266513e-11]], dtype=float32)>