In [1]:
import tensorflow as tf

from LorisBallsBasedModel import *

In [2]:
class SingleCell(tf.keras.Model):
    def __init__(self,
                 cell,
                 nbr_iteration=2,
                 **kwargs):
        super().__init__(**kwargs)
        self.cell = cell
        self.nbr_iteration = nbr_iteration
        
    def call(self, inputs):
        states = [tf.zeros(tf.shape(inputs)), tf.zeros(tf.shape(inputs))]
        
        for i in range(self.nbr_iteration):
            inputs, states = self.cell([inputs, states])
        
        return inputs
    
cell = LSTMCell(activation='linear') 
model = SingleCell(cell)

inputs = tf.random.normal([8, 2])
model.predict(inputs)

array([[ 0.04083603,  0.09778681],
       [ 0.01727492,  0.16136388],
       [-0.00556369, -0.01796418],
       [ 0.01753095,  0.05396003],
       [-0.01229398,  0.10908908],
       [ 0.01706155,  0.05024909],
       [ 0.0024769 ,  0.10849177],
       [-0.00155358,  0.09660954]], dtype=float32)

In [3]:
model.compile(loss='mse',
              optimizer=tf.keras.optimizers.Adam(learning_rate=0.002))

history = model.fit(inputs,
                    inputs,
                    epochs=5000,
                    verbose=0)

model.predict(inputs)

array([[-2.0177    ,  1.4774193 ],
       [ 1.2205617 ,  1.3807752 ],
       [-0.05494324, -0.28314453],
       [-0.27840167,  1.4333214 ],
       [ 1.1680549 ,  0.25134298],
       [-0.28637686,  1.3422794 ],
       [ 0.99207824,  0.65666425],
       [ 0.93523496,  0.49036223]], dtype=float32)

In [4]:
inputs

<tf.Tensor: shape=(8, 2), dtype=float32, numpy=
array([[-2.0178344 ,  1.4774421 ],
       [ 1.2231233 ,  1.3797572 ],
       [-0.05651899, -0.28283364],
       [-0.28334707,  1.4343457 ],
       [ 1.1709664 ,  0.24858375],
       [-0.28084162,  1.341081  ],
       [ 0.984803  ,  0.6582165 ],
       [ 0.93543744,  0.49322262]], dtype=float32)>