In [1]:
from LorisBallsBasedModel import *
import tensorflow as tf
import pandas as pd
import numpy as np

In [2]:
X = np.random.uniform(0, 1, 15000).reshape(1000, 3, 5)  # 1000 examples of 3 inputs with 5 units
X[:3]

array([[[0.13498262, 0.47517149, 0.88161638, 0.63402138, 0.6583013 ],
        [0.07682002, 0.77631968, 0.29075367, 0.71366115, 0.804285  ],
        [0.75048788, 0.73127157, 0.69739607, 0.75339788, 0.47649073]],

       [[0.49741393, 0.75793651, 0.22915239, 0.37274272, 0.19763157],
        [0.52692728, 0.19304137, 0.46184749, 0.89550328, 0.69598531],
        [0.72855932, 0.09265025, 0.34153415, 0.15115517, 0.34954412]],

       [[0.03718671, 0.52187068, 0.84935084, 0.10127317, 0.99159591],
        [0.51642217, 0.780112  , 0.35976409, 0.49676694, 0.7354944 ],
        [0.03878133, 0.63926713, 0.89193795, 0.52178485, 0.56306152]]])

In [3]:
y = 2*X[:, 0]
y[:3]

array([[0.26996524, 0.95034298, 1.76323275, 1.26804277, 1.31660259],
       [0.99482786, 1.51587301, 0.45830478, 0.74548543, 0.39526313],
       [0.07437341, 1.04374135, 1.69870168, 0.20254634, 1.98319181]])

In [4]:
train_tensor = tf.data.Dataset.from_tensor_slices((X[:900],
                                             y[:900])).batch(100)
train_tensor

<BatchDataset shapes: ((None, 3, 5), (None, 5)), types: (tf.float64, tf.float64)>

In [5]:
model = SingleLayerPerceptron(WeightedAdd())

In [6]:
model.compile(loss='MSE', optimizer=tf.keras.optimizers.Adam(learning_rate=0.05), metrics=['acc'])

In [7]:
history = model.fit(train_tensor, epochs=100, verbose=1)

Epoch 1/100


TypeError: in user code:

    File "C:\Users\loris\.virtualenvs\LorisBallsBasedModel-TtjRD8IM\lib\site-packages\keras\engine\training.py", line 878, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\loris\.virtualenvs\LorisBallsBasedModel-TtjRD8IM\lib\site-packages\keras\engine\training.py", line 867, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\loris\.virtualenvs\LorisBallsBasedModel-TtjRD8IM\lib\site-packages\keras\engine\training.py", line 860, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\loris\.virtualenvs\LorisBallsBasedModel-TtjRD8IM\lib\site-packages\keras\engine\training.py", line 808, in train_step
        y_pred = self(x, training=True)
    File "C:\Users\loris\.virtualenvs\LorisBallsBasedModel-TtjRD8IM\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None

    TypeError: Exception encountered when calling layer "single_layer_perceptron" (type SingleLayerPerceptron).
    
    in user code:
    
        File "C:\Users\loris\Desktop\LorisBallsBasedModel\LorisBallsBasedModel\Models\Models.py", line 18, in call  *
            return self.output_layer(inputs)
        File "C:\Users\loris\.virtualenvs\LorisBallsBasedModel-TtjRD8IM\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler  **
            raise e.with_traceback(filtered_tb) from None
        File "C:\Users\loris\Desktop\LorisBallsBasedModel\LorisBallsBasedModel\Layers\WeightedAdd.py", line 33, in build
            shape=[len(input_shape), input_shape[0][1]],  # input_shape[1:]
    
        TypeError: 'NoneType' object is not subscriptable
    
    
    Call arguments received:
      • inputs=tf.Tensor(shape=(None, 3, 5), dtype=float32)


In [8]:
X[997:]

array([[[0.86122472, 0.22580838, 0.42386405, 0.0216878 , 0.15576156],
        [0.11411075, 0.57759462, 0.17148   , 0.98270199, 0.28938745],
        [0.25360702, 0.27060228, 0.8966886 , 0.76571019, 0.79201095]],

       [[0.50183875, 0.74277787, 0.59644162, 0.82376336, 0.93275458],
        [0.72829698, 0.56454082, 0.99812376, 0.87363334, 0.88027723],
        [0.00477643, 0.12431232, 0.28529818, 0.63834148, 0.98535408]],

       [[0.23641884, 0.86345746, 0.12301881, 0.23052985, 0.751445  ],
        [0.68423116, 0.1367175 , 0.37391749, 0.76047664, 0.49765767],
        [0.64060655, 0.70324328, 0.91588432, 0.58694065, 0.57312428]]])

In [9]:
y[997:]

array([[1.72244944, 0.45161676, 0.8477281 , 0.0433756 , 0.31152312],
       [1.0036775 , 1.48555573, 1.19288324, 1.64752672, 1.86550916],
       [0.47283768, 1.72691492, 0.24603763, 0.4610597 , 1.50288999]])

In [10]:
model.output_layer.kernel

<tf.Variable 'single_layer_perceptron/weighted_add_1/kernel:0' shape=(3, 5) dtype=float32, numpy=
array([[ 2.00000000e+00,  2.00000000e+00,  2.00000000e+00,
         2.00000024e+00,  2.00000000e+00],
       [ 6.12679685e-10,  3.81341431e-10, -2.92239011e-10,
        -9.79291457e-08,  2.30669195e-09],
       [-4.39656311e-09, -7.64197317e-10,  6.17050022e-10,
        -1.02515756e-07,  1.77043658e-09]], dtype=float32)>

In [11]:
model(X[997:])

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1.7224494 , 0.45161676, 0.84772813, 0.04337543, 0.3115231 ],
       [1.0036775 , 1.4855558 , 1.1928833 , 1.6475267 , 1.8655092 ],
       [0.4728377 , 1.7269149 , 0.24603763, 0.46105963, 1.50289   ]],
      dtype=float32)>

In [18]:
x1 = tf.reshape(tf.random.uniform(shape=[5000], minval=0., maxval=1.), (1000, 5))
x2 = tf.reshape(tf.random.uniform(shape=[5000], minval=0., maxval=1.), (1000, 5))
x3 = tf.reshape(tf.random.uniform(shape=[5000], minval=0., maxval=1.), (1000, 5))
X = [x1, x2, x3]

w = tf.random.uniform(shape=[len(X), tf.shape(X[0])[1]])
w

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0.36421585, 0.14530468, 0.19152474, 0.8461149 , 0.74449015],
       [0.04573905, 0.98572075, 0.46673226, 0.49774492, 0.08742237],
       [0.29016173, 0.11728024, 0.77295566, 0.76460123, 0.71802795]],
      dtype=float32)>

In [19]:
X

[<tf.Tensor: shape=(1000, 5), dtype=float32, numpy=
 array([[0.40466678, 0.6989825 , 0.44667256, 0.816221  , 0.2241062 ],
        [0.31510317, 0.83118355, 0.97546375, 0.25199723, 0.828308  ],
        [0.924206  , 0.893185  , 0.01773822, 0.29097462, 0.61092985],
        ...,
        [0.5536487 , 0.65853333, 0.42345095, 0.47227907, 0.4062692 ],
        [0.09735441, 0.16025996, 0.7994375 , 0.31774807, 0.5523515 ],
        [0.7476336 , 0.89062357, 0.2963376 , 0.47071826, 0.01007354]],
       dtype=float32)>,
 <tf.Tensor: shape=(1000, 5), dtype=float32, numpy=
 array([[0.7116833 , 0.32131886, 0.05764663, 0.61881876, 0.27140868],
        [0.38855195, 0.12586868, 0.087286  , 0.30123794, 0.0897373 ],
        [0.71636903, 0.7459885 , 0.6558927 , 0.52339244, 0.04718828],
        ...,
        [0.9055846 , 0.7475393 , 0.64103055, 0.2497592 , 0.30053842],
        [0.5842024 , 0.21468055, 0.267882  , 0.8869586 , 0.30686784],
        [0.06758857, 0.19177043, 0.863124  , 0.48738587, 0.13183379]],
    

In [20]:
tf.concat(
    X,
    axis=1)

<tf.Tensor: shape=(1000, 15), dtype=float32, numpy=
array([[0.40466678, 0.6989825 , 0.44667256, ..., 0.79183173, 0.29482305,
        0.6094078 ],
       [0.31510317, 0.83118355, 0.97546375, ..., 0.37653017, 0.00200415,
        0.49947524],
       [0.924206  , 0.893185  , 0.01773822, ..., 0.6201571 , 0.9926623 ,
        0.82481694],
       ...,
       [0.5536487 , 0.65853333, 0.42345095, ..., 0.30770922, 0.1847887 ,
        0.13644505],
       [0.09735441, 0.16025996, 0.7994375 , ..., 0.7083125 , 0.44526935,
        0.9447199 ],
       [0.7476336 , 0.89062357, 0.2963376 , ..., 0.48058462, 0.6674324 ,
        0.06787646]], dtype=float32)>

In [21]:
X_conc= tf.reshape(
    tf.concat(
        X,
        axis=1),
    (-1, len(X), tf.shape(X[0])[-1]))

X_conc

<tf.Tensor: shape=(1000, 3, 5), dtype=float32, numpy=
array([[[0.40466678, 0.6989825 , 0.44667256, 0.816221  , 0.2241062 ],
        [0.7116833 , 0.32131886, 0.05764663, 0.61881876, 0.27140868],
        [0.70256746, 0.07546937, 0.79183173, 0.29482305, 0.6094078 ]],

       [[0.31510317, 0.83118355, 0.97546375, 0.25199723, 0.828308  ],
        [0.38855195, 0.12586868, 0.087286  , 0.30123794, 0.0897373 ],
        [0.9778483 , 0.15710258, 0.37653017, 0.00200415, 0.49947524]],

       [[0.924206  , 0.893185  , 0.01773822, 0.29097462, 0.61092985],
        [0.71636903, 0.7459885 , 0.6558927 , 0.52339244, 0.04718828],
        [0.44500685, 0.58725905, 0.6201571 , 0.9926623 , 0.82481694]],

       ...,

       [[0.5536487 , 0.65853333, 0.42345095, 0.47227907, 0.4062692 ],
        [0.9055846 , 0.7475393 , 0.64103055, 0.2497592 , 0.30053842],
        [0.86959505, 0.7735857 , 0.30770922, 0.1847887 , 0.13644505]],

       [[0.09735441, 0.16025996, 0.7994375 , 0.31774807, 0.5523515 ],
        [0.5842

In [23]:
m = tf.multiply(X_conc, w)
m

<tf.Tensor: shape=(1000, 3, 5), dtype=float32, numpy=
array([[[0.14738606, 0.10156543, 0.08554885, 0.6906167 , 0.16684484],
        [0.03255172, 0.31673068, 0.02690554, 0.3080139 , 0.02372719],
        [0.20385818, 0.00885107, 0.61205083, 0.22542207, 0.43757182]],

       [[0.11476557, 0.12077486, 0.18682544, 0.2132186 , 0.61666715],
        [0.017772  , 0.12407137, 0.04073919, 0.14993966, 0.00784505],
        [0.28373414, 0.01842503, 0.29104114, 0.00153237, 0.35863718]],

       [[0.3366105 , 0.12978396, 0.00339731, 0.24619795, 0.45483124],
        [0.03276604, 0.73533636, 0.3061263 , 0.26051593, 0.00412531],
        [0.12912396, 0.06887388, 0.47935396, 0.7589908 , 0.59224164]],

       ...,

       [[0.20164764, 0.09568798, 0.08110134, 0.39960235, 0.3024634 ],
        [0.04142058, 0.736865  , 0.29918963, 0.12431637, 0.02627378],
        [0.2523232 , 0.09072632, 0.23784558, 0.14128967, 0.09797136]],

       [[0.03545802, 0.02328652, 0.15311207, 0.26885137, 0.41122022],
        [0.0267

In [24]:
tf.reduce_sum(m, axis=1)

<tf.Tensor: shape=(1000, 5), dtype=float32, numpy=
array([[0.38379598, 0.42714718, 0.72450525, 1.2240527 , 0.62814385],
       [0.41627172, 0.26327124, 0.51860577, 0.36469063, 0.9831494 ],
       [0.4985005 , 0.9339942 , 0.7888776 , 1.2657046 , 1.0511982 ],
       ...,
       [0.49539143, 0.9232793 , 0.6181365 , 0.6652084 , 0.42670855],
       [0.27574766, 0.3021204 , 0.82563543, 1.050784  , 1.1163826 ],
       [0.36739936, 0.34757864, 0.8310744 , 1.1511953 , 0.06776207]],
      dtype=float32)>