In [1]:
from LorisBallsBasedModel import *
import tensorflow as tf
import pandas as pd
import numpy as np

In [3]:
X = np.random.uniform(0, 1, 15000).reshape(1000, 3, 5)  # 1000 examples of 3 inputs with 5 units
X[:3]

array([[[0.43145679, 0.97570656, 0.75873439, 0.27402104, 0.18655671],
        [0.51127493, 0.35222609, 0.23952419, 0.52390446, 0.16892806],
        [0.32918968, 0.90088383, 0.54816791, 0.01405801, 0.91805119]],

       [[0.52169685, 0.5985767 , 0.42967079, 0.78397594, 0.93716863],
        [0.76823697, 0.68179614, 0.07370409, 0.54940427, 0.23209212],
        [0.18241437, 0.67942613, 0.31564113, 0.59792144, 0.44596879]],

       [[0.08659491, 0.11539696, 0.29458635, 0.99521927, 0.73223794],
        [0.71887455, 0.50897146, 0.47359687, 0.17182479, 0.94674864],
        [0.42182421, 0.63285984, 0.2920186 , 0.73454551, 0.10865183]]])

In [4]:
y = 2*X[:, 0]
y[:3]

array([[0.86291358, 1.95141313, 1.51746878, 0.54804208, 0.37311343],
       [1.0433937 , 1.1971534 , 0.85934158, 1.56795187, 1.87433725],
       [0.17318982, 0.23079392, 0.58917269, 1.99043854, 1.46447588]])

In [5]:
train_tensor = tf.data.Dataset.from_tensor_slices((X[:900],
                                             y[:900])).batch(100)
train_tensor

<BatchDataset shapes: ((None, 3, 5), (None, 5)), types: (tf.float64, tf.float64)>

In [6]:
model = SingleLayerPerceptron(WeightedAdd())

In [7]:
model.compile(loss='MSE', optimizer=tf.keras.optimizers.Adam(learning_rate=0.05), metrics=['acc'])

In [8]:
history = model.fit(train_tensor, epochs=100, verbose=1)

Epoch 1/100
9/9 [==============================] - 0s 1ms/step - loss: 0.3121 - acc: 0.4367
Epoch 2/100
9/9 [==============================] - 0s 791us/step - loss: 0.1681 - acc: 0.5678
Epoch 3/100
9/9 [==============================] - 0s 2ms/step - loss: 0.0813 - acc: 0.7156
Epoch 4/100
9/9 [==============================] - 0s 4ms/step - loss: 0.0342 - acc: 0.8178
Epoch 5/100
9/9 [==============================] - 0s 2ms/step - loss: 0.0102 - acc: 0.9200
Epoch 6/100
9/9 [==============================] - 0s 2ms/step - loss: 0.0021 - acc: 0.9756
Epoch 7/100
9/9 [==============================] - 0s 2ms/step - loss: 1.7744e-04 - acc: 0.9867
Epoch 8/100
9/9 [==============================] - 0s 2ms/step - loss: 1.7402e-04 - acc: 0.9900
Epoch 9/100
9/9 [==============================] - 0s 1ms/step - loss: 2.1704e-04 - acc: 0.9911
Epoch 10/100
9/9 [==============================] - 0s 2ms/step - loss: 1.2139e-04 - acc: 0.9933
Epoch 11/100
9/9 [==============================] - 0s 2ms/st

In [9]:
X[997:]

array([[[0.84969753, 0.72416857, 0.76563913, 0.48505634, 0.79058194],
        [0.52182086, 0.22153548, 0.34960205, 0.85392616, 0.56109413],
        [0.46370921, 0.09468385, 0.30542603, 0.31840359, 0.4742597 ]],

       [[0.41657991, 0.78250945, 0.78516888, 0.5087062 , 0.97614571],
        [0.37928737, 0.10732002, 0.67779973, 0.23162448, 0.47655806],
        [0.94567329, 0.6985909 , 0.65955011, 0.56346736, 0.26686972]],

       [[0.97187022, 0.24123218, 0.37298617, 0.6232955 , 0.40407895],
        [0.19308549, 0.71371597, 0.65006761, 0.62667666, 0.99055032],
        [0.89127176, 0.79607503, 0.07589933, 0.5104792 , 0.55741613]]])

In [10]:
y[997:]

array([[1.69939505, 1.44833714, 1.53127826, 0.97011268, 1.58116388],
       [0.83315982, 1.5650189 , 1.57033777, 1.0174124 , 1.95229141],
       [1.94374044, 0.48246435, 0.74597233, 1.246591  , 0.80815791]])

In [11]:
model.output_layer.kernel

<tf.Variable 'single_layer_perceptron/weighted_add/kernel:0' shape=(3, 5) dtype=float32, numpy=
array([[ 2.0000000e+00,  2.0000000e+00,  2.0000000e+00,  2.0000000e+00,
         2.0000000e+00],
       [-8.7151458e-10, -5.6356069e-11, -1.7602714e-09, -4.9302140e-10,
        -5.1894661e-10],
       [ 7.5119311e-10, -3.8047601e-10,  2.8509670e-10,  8.7271679e-10,
         3.1983577e-10]], dtype=float32)>

In [12]:
model(X[997:])

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1.6993951 , 1.4483372 , 1.5312783 , 0.9701127 , 1.5811639 ],
       [0.8331598 , 1.5650189 , 1.5703378 , 1.0174124 , 1.9522914 ],
       [1.9437405 , 0.48246434, 0.74597234, 1.246591  , 0.8081579 ]],
      dtype=float32)>