In [1]:
from LorisBallsBasedModel import *
import tensorflow as tf
import pandas as pd
import numpy as np

In [2]:
X = [tf.random.uniform((10000, 3)),
     tf.random.uniform((10000, 3)),
     tf.random.uniform((10000, 3))]

X

[<tf.Tensor: shape=(10000, 3), dtype=float32, numpy=
 array([[0.82568264, 0.6833166 , 0.08656716],
        [0.23693013, 0.45566738, 0.4416114 ],
        [0.9518081 , 0.55162776, 0.11626863],
        ...,
        [0.387002  , 0.541911  , 0.01167607],
        [0.42891407, 0.02905202, 0.2867632 ],
        [0.12025082, 0.93278515, 0.23941767]], dtype=float32)>,
 <tf.Tensor: shape=(10000, 3), dtype=float32, numpy=
 array([[0.9107537 , 0.4355862 , 0.53915966],
        [0.7872293 , 0.7199416 , 0.33906543],
        [0.8757087 , 0.38691723, 0.18217754],
        ...,
        [0.4179027 , 0.5245608 , 0.19491994],
        [0.06839633, 0.124421  , 0.5519062 ],
        [0.9213165 , 0.9458605 , 0.90585864]], dtype=float32)>,
 <tf.Tensor: shape=(10000, 3), dtype=float32, numpy=
 array([[0.15683877, 0.1645397 , 0.2593416 ],
        [0.9071741 , 0.04309106, 0.81106186],
        [0.8176296 , 0.41427934, 0.43113613],
        ...,
        [0.74802995, 0.9275608 , 0.25861728],
        [0.15249658, 0.2587285

In [3]:
y = 2*X[0]

y

<tf.Tensor: shape=(10000, 3), dtype=float32, numpy=
array([[1.6513653 , 1.3666332 , 0.17313433],
       [0.47386026, 0.91133475, 0.8832228 ],
       [1.9036162 , 1.1032555 , 0.23253727],
       ...,
       [0.774004  , 1.083822  , 0.02335215],
       [0.85782814, 0.05810404, 0.5735264 ],
       [0.24050164, 1.8655703 , 0.47883534]], dtype=float32)>

In [4]:
model = SingleLayerPerceptron(WeightedAdd(1))
model.compile(loss='mse', optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), metrics=['acc'])
model.fit(X, y, epochs=50, verbose=1)

Epoch 1/50
313/313 [==============================] - 1s 1ms/step - loss: 0.2982 - acc: 0.5886
Epoch 2/50
313/313 [==============================] - 0s 1ms/step - loss: 0.1584 - acc: 0.6661
Epoch 3/50
313/313 [==============================] - 0s 1ms/step - loss: 0.0961 - acc: 0.7488
Epoch 4/50
313/313 [==============================] - 0s 1ms/step - loss: 0.0552 - acc: 0.8181
Epoch 5/50
313/313 [==============================] - 0s 1ms/step - loss: 0.0298 - acc: 0.8668
Epoch 6/50
313/313 [==============================] - 0s 1ms/step - loss: 0.0152 - acc: 0.9044
Epoch 7/50
313/313 [==============================] - 0s 1ms/step - loss: 0.0074 - acc: 0.9328
Epoch 8/50
313/313 [==============================] - 0s 1ms/step - loss: 0.0035 - acc: 0.9531A: 0s - loss: 0.0045 - acc: 
Epoch 9/50
313/313 [==============================] - 0s 1ms/step - loss: 0.0016 - acc: 0.9674
Epoch 10/50
313/313 [==============================] - 0s 1ms/step - loss: 7.4275e-04 - acc: 0.9784
Epoch 11/50
313/3

In [5]:
model.output_layer.kernel

<tf.Variable 'single_layer_perceptron/weighted_add_2/kernel:0' shape=(3, 3) dtype=float32, numpy=
array([[ 2.0000000e+00,  2.0000000e+00,  2.0000000e+00],
       [ 2.6705839e-11,  5.4049935e-11,  3.2519296e-11],
       [ 2.8673900e-11, -1.3488539e-12,  3.8252679e-11]], dtype=float32)>